import Model from 'ember-data/model';

export default Model.extend({
  username: DS.attr(), //this must be identical to BGG username
  firstName: DS.attr(),
  lastName: DS.attr(),
  address: DS.attr(),
  collection: DS.hasMany('game', {inverse:"ownedBy"}, {async:true}),
  high: DS.hasMany('game', {inverse:null}, {async:true}), //priority to play game
  medium: DS.hasMany('game', {inverse:null}, {async:true}),
  low: DS.hasMany('game', {inverse:null}, {async:true}),
  lat: DS.attr('number'), //generated by google maps geocoding
  lng: DS.attr('number'),
  email: DS.attr(),
  groups: DS.hasMany('group', {inverse:"members"}, {async:true}),
  host: DS.attr('boolean'),
  notes: DS.attr()
});
